image: docker:19.03.12
services:
  - docker:19.03.12-dind

stages:
  - build

variables:
  DOCKER_TAG: "latest"
  IMAGE_NAME: "ai.lr-classifier"
  PROJECT_PATH: "registry.gitlab.com/a2ds/ai/fundus/left-right-fundus-classification"

before_script:
  - apk update && apk add wget
  - docker login -u $username -p $password registry.gitlab.com

build:
  stage: build
  script:
    - docker build -t $IMAGE_NAME:$DOCKER_TAG -f dockers/Dockerfile .
    - docker tag $IMAGE_NAME:$DOCKER_TAG $PROJECT_PATH/$IMAGE_NAME:$DOCKER_TAG
    - docker push $PROJECT_PATH/$IMAGE_NAME:$DOCKER_TAG

