FROM nvidia/cuda:9.0-cudnn7-runtime-ubuntu16.04

RUN apt-get -y update && \
    apt-get -y install \
    python3 \
    python3-dev \
    wget

RUN wget https://bootstrap.pypa.io/get-pip.py && \
    python3 get-pip.py && \
    rm get-pip.py

COPY src/* /src/
COPY requirements.txt /requirements.txt
COPY app.py /app.py
COPY download_model.py /download_model.py

RUN pip3 install -r requirements.txt
RUN python3 download_model.py

CMD ["gunicorn", "-b", "0.0.0.0:5000", "app"]
